<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" ignored="3" name="Test(failed)" tests="1" failures="1" timestamp="2022-04-14T18:14:48 IST" time="25.392" errors="0">
  <testcase name="verifyholdings" time="2.292" classname="tests.Testcase001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://kite.zerodha.com/holdin] but found [https://kite.zerodha.com/holdings]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://kite.zerodha.com/holdin] but found [https://kite.zerodha.com/holdings]
at tests.Testcase001.verifyholdings(Testcase001.java:85)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyholdings -->
  <testcase name="verifydashboard" time="0.0" classname="tests.Testcase001">
    <ignored/>
  </testcase> <!-- verifydashboard -->
  <testcase name="verifyorders" time="0.0" classname="tests.Testcase001">
    <ignored/>
  </testcase> <!-- verifyorders -->
  <testcase name="verifyfunds" time="0.0" classname="tests.Testcase001">
    <ignored/>
  </testcase> <!-- verifyfunds -->
</testsuite> <!-- Test(failed) -->
